# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 600)
        font = QFont()
        font.setFamily(u"Malgun Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.action_New = QAction(MainWindow)
        self.action_New.setObjectName(u"action_New")
        self.action_Open = QAction(MainWindow)
        self.action_Open.setObjectName(u"action_Open")
        self.action_Open_Recent = QAction(MainWindow)
        self.action_Open_Recent.setObjectName(u"action_Open_Recent")
        self.action_Save = QAction(MainWindow)
        self.action_Save.setObjectName(u"action_Save")
        self.action_Save.setCheckable(True)
        self.action_Exit = QAction(MainWindow)
        self.action_Exit.setObjectName(u"action_Exit")
        self.action_New_2 = QAction(MainWindow)
        self.action_New_2.setObjectName(u"action_New_2")
        self.action_Open_2 = QAction(MainWindow)
        self.action_Open_2.setObjectName(u"action_Open_2")
        self.action_Exit_2 = QAction(MainWindow)
        self.action_Exit_2.setObjectName(u"action_Exit_2")
        self.action_Open_All = QAction(MainWindow)
        self.action_Open_All.setObjectName(u"action_Open_All")
        self.action_Save_As = QAction(MainWindow)
        self.action_Save_As.setObjectName(u"action_Save_As")
        self.action_New_3 = QAction(MainWindow)
        self.action_New_3.setObjectName(u"action_New_3")
        self.action_Open_3 = QAction(MainWindow)
        self.action_Open_3.setObjectName(u"action_Open_3")
        self.action_Exit_3 = QAction(MainWindow)
        self.action_Exit_3.setObjectName(u"action_Exit_3")
        self.action_Open_All_2 = QAction(MainWindow)
        self.action_Open_All_2.setObjectName(u"action_Open_All_2")
        self.action_Save_as = QAction(MainWindow)
        self.action_Save_as.setObjectName(u"action_Save_as")
        self.action_Copy = QAction(MainWindow)
        self.action_Copy.setObjectName(u"action_Copy")
        self.action_Cut = QAction(MainWindow)
        self.action_Cut.setObjectName(u"action_Cut")
        self.action_Paste = QAction(MainWindow)
        self.action_Paste.setObjectName(u"action_Paste")
        self.action_abut = QAction(MainWindow)
        self.action_abut.setObjectName(u"action_abut")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.horizontalLayout = QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(1, 1, 1, 1)
        self.textEdit = QTextEdit(self.centralwidget)
        self.textEdit.setObjectName(u"textEdit")

        self.horizontalLayout.addWidget(self.textEdit)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 27))
        self.menu_File = QMenu(self.menubar)
        self.menu_File.setObjectName(u"menu_File")
        self.menu_Open_Recent = QMenu(self.menu_File)
        self.menu_Open_Recent.setObjectName(u"menu_Open_Recent")
        self.menu_Save = QMenu(self.menu_File)
        self.menu_Save.setObjectName(u"menu_Save")
        self.menu_Edit = QMenu(self.menubar)
        self.menu_Edit.setObjectName(u"menu_Edit")
        self.menu_Help = QMenu(self.menubar)
        self.menu_Help.setObjectName(u"menu_Help")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBar)

        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())
        self.menu_File.addAction(self.action_New_3)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Open_3)
        self.menu_File.addAction(self.menu_Open_Recent.menuAction())
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.menu_Save.menuAction())
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Exit_3)
        self.menu_File.addSeparator()
        self.menu_Open_Recent.addAction(self.action_Open_All_2)
        self.menu_Open_Recent.addSeparator()
        self.menu_Save.addSeparator()
        self.menu_Edit.addAction(self.action_Copy)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.action_Cut)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.action_Paste)
        self.menu_Help.addAction(self.action_abut)
        self.menu_Help.addSeparator()

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.action_New.setText(QCoreApplication.translate("MainWindow", u"&New...", None))
#if QT_CONFIG(tooltip)
        self.action_New.setToolTip(QCoreApplication.translate("MainWindow", u"New document", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_New.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.action_Open.setText(QCoreApplication.translate("MainWindow", u"&Open...", None))
#if QT_CONFIG(shortcut)
        self.action_Open.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.action_Open_Recent.setText(QCoreApplication.translate("MainWindow", u"&Open Recent", None))
        self.action_Save.setText(QCoreApplication.translate("MainWindow", u"&Save...", None))
#if QT_CONFIG(shortcut)
        self.action_Save.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.action_Exit.setText(QCoreApplication.translate("MainWindow", u"&Exit...", None))
#if QT_CONFIG(shortcut)
        self.action_Exit.setShortcut(QCoreApplication.translate("MainWindow", u"Esc", None))
#endif // QT_CONFIG(shortcut)
        self.action_New_2.setText(QCoreApplication.translate("MainWindow", u"&New", None))
        self.action_Open_2.setText(QCoreApplication.translate("MainWindow", u"&Open", None))
        self.action_Exit_2.setText(QCoreApplication.translate("MainWindow", u"&Exit", None))
        self.action_Open_All.setText(QCoreApplication.translate("MainWindow", u"&Open All", None))
        self.action_Save_As.setText(QCoreApplication.translate("MainWindow", u"&Save As", None))
#if QT_CONFIG(shortcut)
        self.action_Save_As.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.action_New_3.setText(QCoreApplication.translate("MainWindow", u"&New", None))
#if QT_CONFIG(tooltip)
        self.action_New_3.setToolTip(QCoreApplication.translate("MainWindow", u"Make a new document", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_New_3.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.action_Open_3.setText(QCoreApplication.translate("MainWindow", u"&Open...", None))
#if QT_CONFIG(tooltip)
        self.action_Open_3.setToolTip(QCoreApplication.translate("MainWindow", u"Open a document", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_Open_3.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.action_Exit_3.setText(QCoreApplication.translate("MainWindow", u"&Exit...", None))
#if QT_CONFIG(shortcut)
        self.action_Exit_3.setShortcut(QCoreApplication.translate("MainWindow", u"Esc", None))
#endif // QT_CONFIG(shortcut)
        self.action_Open_All_2.setText(QCoreApplication.translate("MainWindow", u"&Open All", None))
        self.action_Save_as.setText(QCoreApplication.translate("MainWindow", u"&Save as..", None))
#if QT_CONFIG(shortcut)
        self.action_Save_as.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.action_Copy.setText(QCoreApplication.translate("MainWindow", u"&Copy...", None))
#if QT_CONFIG(shortcut)
        self.action_Copy.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+C", None))
#endif // QT_CONFIG(shortcut)
        self.action_Cut.setText(QCoreApplication.translate("MainWindow", u"&Cut...", None))
#if QT_CONFIG(shortcut)
        self.action_Cut.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+X", None))
#endif // QT_CONFIG(shortcut)
        self.action_Paste.setText(QCoreApplication.translate("MainWindow", u"&Paste...", None))
#if QT_CONFIG(shortcut)
        self.action_Paste.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+V", None))
#endif // QT_CONFIG(shortcut)
        self.action_abut.setText(QCoreApplication.translate("MainWindow", u"&About...", None))
        self.menu_File.setTitle(QCoreApplication.translate("MainWindow", u"&File", None))
        self.menu_Open_Recent.setTitle(QCoreApplication.translate("MainWindow", u"&Open Recent", None))
        self.menu_Save.setTitle(QCoreApplication.translate("MainWindow", u"&Save", None))
        self.menu_Edit.setTitle(QCoreApplication.translate("MainWindow", u"&Edit", None))
        self.menu_Help.setTitle(QCoreApplication.translate("MainWindow", u"&Help", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi

